security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OPER:    ROLE_USER
        ROLE_ADMIN:   ROLE_OPER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
                csrf_provider:  security.csrf.token_manager
                login_path :    fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                default_target_path : /game/
                remember_me:    true
            remember_me:
                key:        %secret%
                lifetime:   30000
            logout:   true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/game_admin/, role: ROLE_ADMIN }
        - { path: ^/game_oper/, role: ROLE_OPER }
        - { path: ^/game/, role: ROLE_USER }